[project]
authors = ["Matthew <matthew@jurenka.software>", "Antony <antony@l3labs.org>"]
entry = "main.sw"
license = "Apache-2.0"
name = "module05_eip712_simple"

[dependencies]
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.6.3" }
zapwallet_consts = { path = "../zapwallet_consts" }
module05_utils = { path = "../lib/module05_utils" }
zap_utils = { path = "../lib/zap_utils" }
io_utils = { path = "../lib/io_utils" }
