[project]
authors = ["Antony <antony@l3labs.org>"]
entry = "main.sw"
license = "Apache-2.0"
name = "zap_manager"

[dependencies]
zapwallet_consts = { path = "../zapwallet_consts" }
ptools = { path = "../ptools" }
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.6.3" }
zap_utils = { path = "../lib/zap_utils" }
io_utils = { path = "../lib/io_utils" }

# for debug:
helpers = { path = "../helpers" }

