[project]
authors = ["Antony <antony@l3labs.org>"]
entry = "main.sw"
license = "Apache-2.0"
name = "module07_sponsor"

[dependencies]
helpers = { path = "../helpers" }
ptools = { path = "../ptools" }
bignum = { path = "../sway-bignum/bignum" }
zapwallet_consts = { path = "../zapwallet_consts" }
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.6.3" }
module07_utils = { path = "../lib/module07_utils" }

