[project]
authors = ["Antony <antony@l3labs.org>"]
entry = "main.sw"
license = "Apache-2.0"
name = "module03_erc20"

[dependencies]
helpers = { path = "../helpers" }

ptools = { path = "../ptools" }
bignum = { path = "../sway-bignum/bignum" }
zapwallet_consts = { path = "../zapwallet_consts" }
module03_utils = { path = "../lib/module03_utils" }
io_utils = { path = "../lib/io_utils" }

