[project]
authors = ["Antony <0xbadc0de@l3labs.org>"]
entry = "main.sw"
license = "Apache-2.0"
name = "module03_erc20"

[dependencies]
zap_utils = { path = "../lib/zap_utils" }
zapwallet_consts = { path = "../zapwallet_consts" }
io_utils = { path = "../lib/io_utils" }

