[project]
authors = ["Antony <antony@l3labs.org>"]
entry = "main.sw"
license = "Apache-2.0"
name = "module04_txidwit"

[dependencies]
zap_utils = { path = "../lib/zap_utils" }
io_utils = { path = "../lib/io_utils" }

