[project]
authors = ["Antony <antony@l3labs.org>"]
entry = "main.sw"
license = "Apache-2.0"
name = "module00_upgrade"

[dependencies]
helpers = { path = "../helpers" }
ptools = { path = "../ptools" }
io_utils = { path = "../lib/io_utils" }
module00_utils = { path = "../lib/module00_utils" }