[workspace]
members = [
  "module00_upgrade",
  "module01_evm_txtype1",
  "module02_evm_txtype2",
  "module03_erc20",
  "module04_txidwit",
  "module05_eip712_simple",
  "module06_eip712_contract",
  "module07_sponsor",
  "module08",
  "master",
  "zap_manager",
  # "tests",
]
