[project]
authors = ["Antony <antony@l3labs.org>"]
entry = "main.sw"
license = "Apache-2.0"
name = "module02_evm_txtype2"

[dependencies]
ptools = { path = "../ptools" }
helpers = { path = "../helpers" }
bignum = { path = "../sway-bignum/bignum" }
zapwallet_consts = { path = "../zapwallet_consts" }
module02_utils = { path = "../lib/module02_utils" }
io_utils = { path = "../lib/io_utils" }
