[project]
authors = ["0xbadc0de <0xbadc0de@l3labs.org>"]
entry = "main.sw"
license = "Apache-2.0"
name = "module_sponsor"

[dependencies]
helpers = { path = "../helpers" }
ptools = { path = "../ptools" }

